accent = "#88C0D0"
cursor = "#D8DEE9"
foreground = "#BBC3D4"
background = "#242933"
selection_foreground = "#E5E9F0"
selection_background = "#3B4252"

color0 = "#191D24"
color1 = "#BF616A"
color2 = "#A3BE8C"
color3 = "#EBCB8B"
color4 = "#81A1C1"
color5 = "#B48EAD"
color6 = "#8FBCBB"
color7 = "#E5E9F0"
color8 = "#3B4252"
color9 = "#C5727A"
color10 = "#B1C89D"
color11 = "#EFD49F"
color12 = "#88C0D0"
color13 = "#BE9DB8"
color14 = "#9FC6C5"
color15 = "#ECEFF4"
